'use client';

import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FileText, Download, Eye, Calendar, BarChart3, X, FileCheck } from 'lucide-react';
import { AppShell } from '@/components/layout/app-shell';
import { ChartCard } from '@/components/dashboard/chart-card';
import { TableSkeleton } from '@/components/shared/skeleton';
import { ErrorBanner } from '@/components/shared/error-banner';
import { EmptyState } from '@/components/shared/empty-state';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { useFetch } from '@/hooks/use-fetch';
import { getReports } from '@/services/api';
import { formatRelativeTime, formatDate } from '@/utils/format';
import { Report } from '@/types';
import { toast } from '@/hooks/use-toast';

export default function ReportsPage() {
  const { data: reportsData, loading, error, refetch } = useFetch(getReports, []);
  const [selectedReport, setSelectedReport] = useState<Report | null>(null);

  const reports: Report[] = reportsData?.reports || reportsData || [];

  const handleDownload = (report: Report) => {
    // Generate a simple text-based report for download
    const content = `
NeuroBudget Financial Report
============================
Title: ${report.title || report.period}
Period: ${report.period}
Generated: ${formatDate(report.created_at || report.date || new Date())}

Summary:
${report.summary || 'No summary available.'}

---
Generated by NeuroBudget AI Financial Copilot
    `.trim();

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `neurobudget-report-${report.period || 'summary'}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast({ title: 'Report downloaded', description: `${report.title || report.period} report saved` });
  };

  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="text-2xl font-bold tracking-tight">Financial Reports</h2>
            <p className="text-sm text-muted-foreground">Monthly summaries and financial insights</p>
          </div>
          <Badge variant="secondary" className="w-fit gap-1.5">
            <FileText className="h-3 w-3" /> {reports.length} reports
          </Badge>
        </div>

        {error && <ErrorBanner message={error} onRetry={refetch} />}

        {/* Financial summary cards */}
        <div className="grid gap-4 sm:grid-cols-3">
          <Card className="glass border-white/5 p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-chart-1/15">
                <FileText className="h-5 w-5 text-chart-1" />
              </div>
              <div>
                <p className="text-2xl font-bold">{reports.length}</p>
                <p className="text-xs text-muted-foreground">Total Reports</p>
              </div>
            </div>
          </Card>
          <Card className="glass border-white/5 p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-chart-2/15">
                <Calendar className="h-5 w-5 text-chart-2" />
              </div>
              <div>
                <p className="text-2xl font-bold">{new Set(reports.map(r => r.period?.slice(0, 7))).size}</p>
                <p className="text-xs text-muted-foreground">Months Covered</p>
              </div>
            </div>
          </Card>
          <Card className="glass border-white/5 p-5">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-chart-4/15">
                <FileCheck className="h-5 w-5 text-chart-4" />
              </div>
              <div>
                <p className="text-2xl font-bold">{reports.filter(r => r.summary).length}</p>
                <p className="text-xs text-muted-foreground">With Summaries</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Reports grid */}
        {loading ? (
          <div className="space-y-3">
            <TableSkeleton rows={4} />
            <TableSkeleton rows={4} />
          </div>
        ) : reports.length > 0 ? (
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
            {reports.map((report, i) => (
              <motion.div
                key={report.id || i}
                initial={{ opacity: 0, y: 16 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.05 }}
              >
                <Card className="group glass border-white/5 p-5 transition-all hover:border-chart-1/20 hover:shadow-lg hover:shadow-chart-1/5">
                  <div className="flex items-start justify-between">
                    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-chart-1/20 to-chart-4/10">
                      <FileText className="h-5 w-5 text-chart-1" />
                    </div>
                    <Badge variant="secondary" className="text-xs">{report.type || 'Monthly'}</Badge>
                  </div>

                  <h3 className="mt-4 font-semibold">{report.title || report.period}</h3>
                  <p className="mt-1 text-xs text-muted-foreground">{report.period}</p>

                  {report.summary && (
                    <p className="mt-3 line-clamp-3 text-sm text-muted-foreground">
                      {report.summary}
                    </p>
                  )}

                  <div className="mt-4 flex items-center justify-between">
                    <span className="text-xs text-muted-foreground">
                      {formatRelativeTime(report.created_at || report.date || new Date())}
                    </span>
                    <div className="flex gap-1.5">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => setSelectedReport(report)}
                        className="h-8 gap-1.5 px-2.5 text-xs"
                      >
                        <Eye className="h-3.5 w-3.5" /> Preview
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => handleDownload(report)}
                        className="h-8 gap-1.5 px-2.5 text-xs"
                      >
                        <Download className="h-3.5 w-3.5" /> PDF
                      </Button>
                    </div>
                  </div>
                </Card>
              </motion.div>
            ))}
          </div>
        ) : (
          <Card className="glass border-white/5">
            <EmptyState
              icon={FileText}
              title="No reports available"
              description="Financial reports will appear here once your backend generates them. Upload transactions and run analysis to create reports."
            />
          </Card>
        )}

        {/* Report preview dialog */}
        <Dialog open={!!selectedReport} onOpenChange={(open) => !open && setSelectedReport(null)}>
          <DialogContent className="glass-strong max-w-2xl border-white/10">
            <DialogHeader>
              <DialogTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-chart-1" />
                {selectedReport?.title || selectedReport?.period}
              </DialogTitle>
            </DialogHeader>
            <div className="space-y-4">
              <div className="flex items-center gap-3">
                <Badge variant="secondary">{selectedReport?.type || 'Monthly'}</Badge>
                <span className="text-sm text-muted-foreground">{selectedReport?.period}</span>
                {selectedReport?.created_at && (
                  <span className="text-xs text-muted-foreground">
                    Generated {formatDate(selectedReport.created_at)}
                  </span>
                )}
              </div>

              <div className="rounded-xl border border-border bg-card/40 p-4">
                <h4 className="mb-2 text-sm font-semibold">Summary</h4>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {selectedReport?.summary || 'No summary available for this report.'}
                </p>
              </div>

              {selectedReport?.data && Object.keys(selectedReport.data).length > 0 && (
                <div className="rounded-xl border border-border bg-card/40 p-4">
                  <h4 className="mb-2 text-sm font-semibold">Report Data</h4>
                  <pre className="text-xs text-muted-foreground overflow-x-auto scrollbar-thin">
                    {JSON.stringify(selectedReport.data, null, 2)}
                  </pre>
                </div>
              )}

              <div className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setSelectedReport(null)}>
                  Close
                </Button>
                {selectedReport && (
                  <Button
                    onClick={() => handleDownload(selectedReport)}
                    className="gap-2 bg-gradient-to-r from-chart-1 to-chart-4 text-white hover:opacity-90"
                  >
                    <Download className="h-4 w-4" /> Download
                  </Button>
                )}
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>
    </AppShell>
  );
}
